name: Black Formatter

on:
  push:
    branches:
      - master
      
jobs:
  linter:
    name: runner / black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: psf/black@stable
        with:
          options: "-l 80"
          src: "./pina"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Format Python code with psf/black push"
          commit-message: ":art: Format Python code with psf/black"
          body: |
            There appear to be some python formatting errors in ${{ github.sha }}. This pull request
            uses the [psf/black](https://github.com/psf/black) formatter to fix these issues.
          base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
          branch: actions/black
