name: "Documentation Deploy"

on: 
  push:
    tags:
      - "*"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Create the new documentation
      uses: ammaraskar/sphinx-action@7.4.7
      with:
        pre-build-command: "python3 -m pip install .[docs]"
        docs-folder: "docs/"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        #deploy_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        publish_dir: ./docs/build/html
        allow_empty_commit: true
