name: Test Sphinx Documentation Build

on:
  pull_request:
    branches:
      - "master"
      - "0.2"
    paths:
      - 'docs/**'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Python dependencies
      run: python3 -m pip install .[doc]

    - name: Build Documentation
      run: |
        make html SPHINXOPTS+='-W'
      working-directory: docs/