name: Test Sphinx Documentation Build

on:
  pull_request:
    branches:
      - "master"
      - "0.2"
    paths:
      - 'docs/**'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Checkout Doc
      uses: ammaraskar/sphinx-action@7.4.7
      with:
        pre-build-command: "python3 -m pip install .[doc]"
        build-command: "make html SPHINXOPTS='-W'"
        docs-folder: "docs/"